/*
* Symbolset
* www.symbolset.com
* Copyright © 2012 Oak Studios LLC
*
* Upload this file to your web server
* and place this before the closing </body> tag.
* <script src="webfonts/ss-social.js"></script>
*/

if(/(MSIE [7-9]\.|Opera.*Version\/(10\.[5-9]|(11|12)\.)|Chrome\/([1-9]|10)\.|Version\/[2-4][\.0-9]+ Safari\/|Version\/(4\.0\.[4-9]|4\.[1-9]|5\.0)[\.0-9]+? Mobile\/.*Safari\/|Android [1-2]\.|BlackBerry.*WebKit)/.test(navigator.userAgent)&&!/(IEMobile)/.test(navigator.userAgent)){var ss_set={"stack overflow":"\uF672","github octocat":"\uF671",githuboctocat:"\uF671",stackoverflow:"\uF672","google plus":"\uF613",kickstarter:"\uF681",foursquare:"\uF690",googleplus:"\uF613",instagram:"\uF641",pinterest:"\uF650",posterous:"\uF623",wordpress:"\uF621","thumbs up":"\uD83D\uDC4D",dribbble:"\uF660",facebook:"\uF610",linkedin:"\uF612",thumbsup:"\uD83D\uDC4D","google +":"\uF613",readmill:"\uF652",envelope:"\u2709",twitter:"\uF611",behance:"\uF661",dropbox:"\uF653",youtube:"\uF630",octocat:"\uF671","google+":"\uF613",approve:"\uD83D\uDC4D",spotify:"\uF6B1","last fm":"\uF6B2",blogger:"\uF622",flickr:"\uF640",tumblr:"\uF620",paypal:"\uF680",lastfm:"\uF6B2",github:"\uF670",svpply:"\uF651",email:"\u2709",skype:"\uF6A0",vimeo:"\uF631",mail:"\u2709",rdio:"\uF6B0",like:"\uD83D\uDC4D",rss:"\uE310"};if(typeof ss_icons!=="object"||typeof ss_icons!=="object"){var ss_icons=ss_set;var ss_keywords=[];for(var i in ss_set){ss_keywords.push(i)}}else{for(var i in ss_set){ss_icons[i]=ss_set[i];ss_keywords.push(i)}}if(typeof ss_legacy!=="function"){!function(d,c){typeof module!="undefined"?module.exports=c():typeof define=="function"&&typeof define.amd=="object"?define(c):this[d]=c()}("ss_ready",function(z){function n(b){o=1;while(b=y.shift()){b()}}var y=[],x,w=!1,v=document,u=v.documentElement,t=u.doScroll,s="DOMContentLoaded",r="addEventListener",q="onreadystatechange",p="readyState",o=/^loade|c/.test(v[p]);return v[r]&&v[r](s,x=function(){v.removeEventListener(s,x,w),n()},w),t&&v.attachEvent(q,x=function(){/^c/.test(v[p])&&(v.detachEvent(q,x),n())}),z=t?function(a){self!=top?o?a():y.push(a):function(){try{u.doScroll("left")}catch(c){return setTimeout(function(){z(a)},50)}a()}()}:function(b){o?b():y.push(b)}});var ss_legacy=function(b){if(!b instanceof Object){return false}if(b.length){for(var a=0;a<b.length;a++){ss_legacy(b[a])}return}if(b.value){b.value=ss_liga(b.value)}else{if(b.nodeValue){b.nodeValue=ss_liga(b.nodeValue)}else{if(b.innerHTML){b.innerHTML=ss_liga(b.innerHTML)}}}};var ss_getElementsByClassName=function(g,h){if(document.querySelectorAll){return document.querySelectorAll("."+h)}var b=[];var f=new RegExp("(^| )"+h+"( |$)");var e=g.getElementsByTagName("*");for(var d=0,c=e.length;d<c;d++){if(f.test(e[d].className)){b.push(e[d])}}return b};var ss_liga=function(b){var a=new RegExp(ss_keywords.join("|").replace(/[-[\]{}()*+?.,\\^$#\s]/g,"\\$&"),"gi");return b.replace(a,function(c){return ss_icons[c.toLowerCase()]})};ss_ready(function(){if(document.getElementsByClassName){ss_legacy(document.getElementsByClassName("ss-icon"))}else{ss_legacy(ss_getElementsByClassName(document.body,"ss-icon"))}})}};